### PR TITLE
feat: new website for searchbox

### PR DESCRIPTION
**Pull request by jyash97**
### TODOS: 

- [x] Footer hover color fix
- [x] Add Links

### Testing
https://www.loom.com/share/1c3a6385b4f3484f8653afae44a615fc

### CODE REVIEW

**Comment by jyash97** [comment]
Updated Site: https://www.loom.com/share/81abff1ee8814f46a40f1cf6074ea023

**Review by siddharthlatest — CHANGES_REQUESTED** [review]
We're almost there, and this is looking really good. 💯

https://www.loom.com/share/b27bb287875d4940a28df7531f1153de

Enumerating the feedback:

- [x] Support button in navbar can use the icon
- [x] Using links instead of buttons for secondary buttons
- [x] The images in the different libraries sections can use extra margin to make them blend. See live website for reference
- [x] Can we move the Github star icon to the navbar? It can show to the left of the Support button
- [x] There's a warning of unused tailwind styles not getting purged

(optional) - Is there a rationale for the Support section to have its content outside the content margins on a larger device screen?

**Comment by jyash97** [comment]
> (optional) - Is there a rationale for the Support section to have its content outside the content margins on a larger device screen?

This is done because we need the full width of blue shades of background and if we limit the height it won't blend well with the background.

**Review by siddharthlatest — COMMENTED** [review]
Functionality wise, this is 💯  now.

**Pull request merged**
